---
# Title: main.yml
#
# Author: bitfinity-nl - L. Rutten
# Owner: IT Operations
# File: tasks/main.yml
#
# Description:
#   Role for configuring OS base settings:
#   - Ubuntu;
#   - Windows;

- name: "Include all .yml variable files"
  include_vars:
    dir: defaults/
    extensions:
      - 'yml'
      - 'yaml'

- name: "Configure Ubuntu"
  import_tasks: "{{ item.taskfile }}"
  with_items:
    - tasks/ubt/01-account-settings.yml
    - tasks/ubt/02-network-settings.yml
    - tasks/ubt/03-security-settings.yml
    - tasks/ubt/04-selfsigned-certificate.yml
  #when: ansible_os_family == "Ubuntu"
  
#- name: "Configure Windows"
#  import_tasks: "{{ item.taskfile }}"
#  with_items:
#    - { taskfile: 'win/01-win-activation.yml' }
#  when: ansible_os_family == "Windows"
