---
# Title: main.yml
#
# Author: bitfinity-nl - L. Rutten
# Owner: IT Operations
# File: tasks/main.yml
#
# Description:
#   Role for configuring OS base settings:
#   - Windows;
#   - Ubuntu;

- name: "Configure Ubuntu"
  import_tasks: ubt/ubt-main.yml
  when: 
    - ansible_os_family == "Windows"
