---
# Title: main.yml
#
# Author: bitfinity-nl - L. Rutten
# Owner: IT Operations
# File: tasks/main.yml
#
# Description:
#   Role for configuring OS base settings:
#   - Ubuntu;
#   - Windows;


- name: "Include defaults"
  include_vars: "{{ item }}"
  with_items:
    - defaults/main.yml
    - defaults/win-settings.yml

- name: "Configure tasks/ubt/01-account-settings.yml"
  include_tasks: "tasks/ubt/01-account-settings.yml"
  when: ansible_distribution == "Ubuntu"
  
- name: "Configure tasks/ubt/02-network-settings.yml"
  include_tasks: "tasks/ubt/02-network-settings.yml"
  when: ansible_distribution == "Ubuntu" 
  
- name: "Configure tasks/ubt/03-security-settings.yml"
  include_tasks: "tasks/ubt/03-security-settings.yml"
  when: ansible_distribution == "Ubuntu"   
  
- name: "Configure tasks/ubt/04-selfsigned-certificate.yml"
  include_tasks: "tasks/ubt/04-selfsigned-certificate.yml"
  when: ansible_distribution == "Ubuntu"   
  
  #with_items:
  #  - tasks/ubt/01-account-settings.yml
  #  - tasks/ubt/02-network-settings.yml
  #  - tasks/ubt/03-security-settings.yml
  #  - tasks/ubt/04-selfsigned-certificate.yml
  when: ansible_distribution == "Ubuntu"
  
- name: "Configure Windows"
  include_tasks: "{{ item.taskfile }}"
  with_items:
    - { taskfile: 'win/01-win-activation.yml' }
  when: ansible_os_family == "Windows"
