---
# Title: main.yml
#
# Author: bitfinity-nl - L. Rutten
# Owner: IT Operations
# File: tasks/main.yml
#
# Description:
#   Role for configuring OS base settings:
#   - Ubuntu;
#   - Windows;

- name: "Include default/win-settings.yml"
  include_vars: "{{ item.varfile}}"
    - { osfamily: 'Windows', varfile: 'defaults/win-settings.yml' }
    
- name: "Configure Ubuntu"
  import_tasks: "{{ item.taskfile }}"
    - { taskfile: 'ubt/01-account-settings.yml' }
    - { taskfile: 'ubt/02-network-settings.yml' }
    - { taskfile: 'ubt/03-security-settings.yml' }
    - { taskfile: 'ubt/04-selfsigned-certificate.yml' }
  when: ansible_os_family == "Ubuntu"
  
- name: "Configure Windows"
  import_tasks: "{{ item.taskfile }}"
  with_items:
    - { taskfile: 'win/01-win-activation.yml' }
  when: ansible_os_family == "Windows"
