---
# Title: main.yml
#
# Author: bitfinity-nl - L. Rutten
# Owner: IT Operations
# File: tasks/main.yml
#
# Description:
#   Playbook for installing InvoiceNinja
#   on a Ubuntu server.

- name: "Create Ansible directory structure"
  file:
    name: /etc/ansible/roles/
    state: directory
    
- name: "Install and configure base settings"
  import_tasks: 01-account-settings.yml

- name: "Configure Network settings"
  import_tasks: 02-network-settings.yml

- name: "Configure security settings"
  import_tasks: 03-security-settings.yml

#- name: "Generate selfsigned certificates"
#  import_tasks: 04-selfsigned-certificate.yml

