---
# Title: role-base
# 
# Author: Bitfinity-NL
# File: tasks/main.yml
#
# Description:
#   Base settings for Ubuntu server on a Proxmox Environment.
#

- name: "Install additional packages"
  apt:
    name: "{{ packages }}"
    state: present
#    update_cache: no
  vars:
    packages:
    - apt-transport-https
    - whois
    - qemu-guest-agent

- name: "Update alle respitories and packages"
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: "Generate temporary password for user {{ base_admin_user }}"
  command: "mkpasswd --method=sha-512 {{ base_admin_pass }}"
  register: encrypted_password
  #become: yes
  
- name: "Add group {{ base_admin_group }} for administrative account {{ base_admin_user }}"
  group:
    name: "{{ base_admin_group }}"
    state: present

- name: "Add local administrative account {{ base_admin_user }}"
  user:
    name: "{{ base_admin_user }}"
    comment: "Local administrative account"
    shell: /bin/bash
    group: "{{ base_admin_group }}"
    groups: sudo
    create_home: yes
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
    password: "{{ encrypted_password.stdout }}"
    update_password: always

- name: "Ensure temporary (cloudinit) user {{ base_temp_user }} does not exists and remove homedirectory"
  user:
    name: "{{ base_temp_user }}"
    state: absent
    remove: yes

- name: "Ensure the group of the temporary (cloudinit) user {{ base_temp_group }} does not exists."
  group:
    name: "{{ base_temp_group }}"
    state: present
    
- name: "Ensure cloudinit file /etc/sudoers.d//90-cloud-init-users does not exists."
  file:
    path: /etc/sudoers.d//90-cloud-init-users
    state: absent
