---
# Title: Networking
#
# Author: bitfinity-nl - L. Rutten
# Owner: bitfinity-nl
# File: tasks/02-network-settings.yml
#
# Description:
#   Playbook voor configuring networking.

- name: "Transfer templates/ubt/01-netcfg-yml.j2 /etc/netplan/01-netcfg.yaml"
  template:
    src: templates/ubt/01-netcfg-yml.j2
    dest: /etc/netplan/01-netcfg.yaml
    owner: root
    group: root
    mode: 0755
    backup: yes
  notify: netplan_apply
