---
# Title: firewall
#
# Author: bitfinity-nl - L. Rutten
# Owner: bitfinity-nl
# File: tasks/ubt/03-security-settings.yml
#
# Description:
#   Playbook voor configuring security settings.

- name: "Add firewall profile for openssh traffic on port 22/tcp and enable firewall"
  ufw:
    rule: allow
    name: OpenSSH
    state: enabled
