---
# Title: Selfsigned certificate
#
# Author: bitfinity-nl - L. Rutten
# Owner: IT Operations
# File: tasks/04-selfsigned-certificate.yml
#
# Description:
#   Playbook for installing InvoiceNinja
#   on a Ubuntu server.

- name: "Install APT packages"
  apt:
    pkg:
    - python3-pip
    
- name: Ensure python OpenSSL dependencies are installed.
  pip:
    name: pyOpenSSL
    state: present
    
- name: Ensure directory exists for local self-signed TLS certs.
  file:
    path: "{{ cert_path }}"
    state: directory

- name: Generate an OpenSSL private key.
  openssl_privatekey:
    path: "{{ cert_private_key }}"

- name: Generate an OpenSSL CSR.
  openssl_csr:
    path: "{{ cert_csr_file }}"
    privatekey_path: "{{ cert_private_key }}"
    common_name: "{{ cert_servername }}"

- name: Generate a Self Signed OpenSSL certificate.
  openssl_certificate:
    path: "{{ cert_fullchain }}"
    privatekey_path: "{{ cert_private_key }}"
    csr_path: "{{ cert_csr_file }}"
    provider: selfsigned
